import os
import datetime

def generate_markdown_report(target, findings, output_file="report.md"):
    """
    Generates a structured security report in Markdown.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"""# Security Assessment Report: {target}
**Date:** {timestamp}
**Agent:** Livion (Autonomous Security Researcher)

## Executive Summary
This report details the findings from an autonomous security assessment conducted by Livion.

## Scope
- Target: {target}
- Assessment Type: Automated Recon & Scanning

## Findings Summary
| Severity | Count |
| --- | --- |
| Critical | {findings.get('critical', 0)} |
| High | {findings.get('high', 0)} |
| Medium | {findings.get('medium', 0)} |
| Low | {findings.get('low', 0)} |
| Informational | {findings.get('info', 0)} |

## Detailed Findings
"""
    
    for issue in findings.get('issues', []):
        report += f"""
### [{issue['severity'].upper()}] {issue['title']}
- **Description:** {issue['description']}
- **Evidence:** 
```
{issue.get('evidence', 'N/A')}
```
- **Remediation:** {issue.get('remediation', 'N/A')}
- **CVSS Score:** {issue.get('cvss', 'N/A')}

---
"""

    report += "\n\n*Generated by Livion Autonomous Agent*"
    
    with open(output_file, 'w') as f:
        f.write(report)
        
    return f"Success: Report generated at {output_file}"
